Maintain Empty Lines Around Export Statements
Gtlogic/gt-eslint-rules pull request #2
Opened 2022-01-17 09:10 UTC by OmarJaroudi

2022-01-27 09:31 UTC, AliGTLogic requested changes
Nicee

2022-01-27 09:31 UTC, AliGTLogic commented on docs/rules/empty-line-around-export.md
> +export const FIRST_CONST = 'first_contsant';
s/contsant/constant

2022-01-27 09:31 UTC, AliGTLogic commented on docs/rules/empty-line-around-export.md
> +export const FIRST_CONST = 'first_contsant';
s/contsant/constant

2022-01-27 12:18 UTC, AliGTLogic approved these changes
Every time you make a typo, the errorists win. (googled this)

2022-05-10 09:31 UTC, khaledsayyed approved these changes

2022-05-10 11:20 UTC, merged